[package]
name = "radion"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/axegon/radion"
readme = "README.md"
description = "RTL-SDR bindings for Rust"

[dependencies]
